/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class PAPUAudioProcessorEditor  : public gin::GinAudioProcessorEditor
{
public:
    PAPUAudioProcessorEditor (PAPUAudioProcessor&);
    ~PAPUAudioProcessorEditor() override;

    //==============================================================================
    void resized() override;
    void paint (Graphics& g) override;

    PAPUAudioProcessor& proc;
    
    gin::TriggeredScope scope { proc.fifo };
    Image logo;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (PAPUAudioProcessorEditor)
};
